<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /Applications/MAMP/htdocs/my-nette-project/app/Presentation/Home/default.latte */
final class Template_d8799a0a8b extends Latte\Runtime\Template
{
	public const Source = '/Applications/MAMP/htdocs/my-nette-project/app/Presentation/Home/default.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<base href="';
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($basePath)) /* line 1 */;
		echo '/">

<h1>';
		echo LR\Filters::escapeHtmlText($message) /* line 3 */;
		echo '</h1>

';
		if ($editing) /* line 5 */ {
			echo '    <h3>Edit user</h3>
';
		} else /* line 7 */ {
			echo '    <h3>Add user</h3>
';
		}
		echo "\n";
		$ʟ_tmp = $this->global->uiControl->getComponent('userForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* line 11 */;

		echo '

<h3>Users list</h3>

<table border="1" cellpadding="5">
    <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Actions</th>
    </tr>

';
		foreach ($users as $u) /* line 27 */ {
			echo '        <tr>
            <td>';
			echo LR\Filters::escapeHtmlText($u->id) /* line 29 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->username) /* line 30 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->first_name) /* line 31 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->last_name) /* line 32 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->email) /* line 33 */;
			echo '</td>
            <td>';
			echo LR\Filters::escapeHtmlText($u->role) /* line 34 */;
			echo '</td>
            <td>
                <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('default', ['id' => $u->id])) /* line 36 */;
			echo '">Edit</a> |
                <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('delete!', ['id' => $u->id])) /* line 37 */;
			echo '" onclick="return confirm(\'Delete this user?\')">Delete</a>
            </td>
        </tr>
';

		}

		echo '</table>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['u' => '27'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
