<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /Applications/MAMP/htdocs/my-nette-project/app/Presentation/Home/templates/Home/default.latte */
final class Template_768c0cbd27 extends Latte\Runtime\Template
{
	public const Source = '/Applications/MAMP/htdocs/my-nette-project/app/Presentation/Home/templates/Home/default.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* line 1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['u' => '46'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<base href="';
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($basePath)) /* line 2 */;
		echo '/">
<link rel="stylesheet" href="';
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($basePath)) /* line 3 */;
		echo '/css/style.css">

<div class="container">
    <h1>Library reservation system</h1>

';
		if (isset($welcome)) /* line 8 */ {
			echo '        <h2>';
			echo LR\Filters::escapeHtmlText($welcome) /* line 9 */;
			echo '</h2>
';
		}
		echo '
    <a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Book:default')) /* line 12 */;
		echo '" class="btn">Správa knih</a>

';
		if (isset($message)) /* line 14 */ {
			echo '        <div class="flash">';
			echo LR\Filters::escapeHtmlText($message) /* line 15 */;
			echo '</div>
';
		}
		echo '
    <div class="form-section" style="margin-top:2rem;">
';
		if ($editing) /* line 19 */ {
			echo '            <h2>Edit users</h2>
';
		} else /* line 21 */ {
			echo '            <h2>Add new users</h2>
';
		}
		echo '
        <div class="form-wrapper">
';
		$ʟ_tmp = $this->global->uiControl->getComponent('userForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* line 26 */;

		echo '        </div>
    </div>

    <div class="list-section" style="margin-top:2rem;">
        <h2>List of users</h2>

        <table border="1" cellpadding="5">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
';
		foreach ($users as $u) /* line 46 */ {
			echo '                    <tr>
                        <td>';
			echo LR\Filters::escapeHtmlText($u->id) /* line 48 */;
			echo '</td>
                        <td>';
			echo LR\Filters::escapeHtmlText($u->username) /* line 49 */;
			echo '</td>
                        <td>';
			echo LR\Filters::escapeHtmlText($u->first_name) /* line 50 */;
			echo '</td>
                        <td>';
			echo LR\Filters::escapeHtmlText($u->last_name) /* line 51 */;
			echo '</td>
                        <td>';
			echo LR\Filters::escapeHtmlText($u->email) /* line 52 */;
			echo '</td>
                        <td>';
			echo LR\Filters::escapeHtmlText($u->role) /* line 53 */;
			echo '</td>
                        <td class="actions">
                            <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('default', ['id' => $u->id])) /* line 55 */;
			echo '" class="btn edit">Edit</a>
                            <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('delete!', ['id' => $u->id])) /* line 56 */;
			echo '"
                               onclick="return confirm(\'Are you sure you want to delete this user?\')"
                               class="btn delete">Delete</a>
                        </td>
                    </tr>
';

		}

		echo "\n";
		if (!count($users)) /* line 63 */ {
			echo '                    <tr>
                        <td colspan="7" style="text-align:center; color:#777;">
                            No users added yet.
                        </td>
                    </tr>
';
		}
		echo '            </tbody>
        </table>
    </div>
</div>
';
	}
}
