<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /Applications/MAMP/htdocs/my-nette-project/app/Presentation/Book/templates/Book/default.latte */
final class Template_da87ccba2d extends Latte\Runtime\Template
{
	public const Source = '/Applications/MAMP/htdocs/my-nette-project/app/Presentation/Book/templates/Book/default.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<base href="';
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($basePath)) /* line 1 */;
		echo '/">
<link rel="stylesheet" href="';
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($basePath)) /* line 2 */;
		echo '/css/style.css">

<div class="container">
    <h1>Správa knih</h1>

';
		if ($editing) /* line 7 */ {
			echo '        <h3>Upravit knihu</h3>
';
		} else /* line 9 */ {
			echo '        <h3>Přidat novou knihu</h3>
';
		}
		echo "\n";
		$ʟ_tmp = $this->global->uiControl->getComponent('bookForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* line 13 */;

		echo '
    <h3>Seznam knih</h3>
    <table>
        <tr>
            <th>ID</th>
            <th>Název</th>
            <th>Autor</th>
            <th>ISBN</th>
            <th>Rok vydání</th>
            <th>Žánr</th>
            <th>Celkem kopií</th>
            <th>Dostupné</th>
            <th>Přidáno</th>
            <th>Akce</th>
        </tr>

';
		foreach ($books as $b) /* line 30 */ {
			echo '            <tr>
                <td>';
			echo LR\Filters::escapeHtmlText($b->id) /* line 32 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->title) /* line 33 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->author) /* line 34 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->isbn) /* line 35 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->publication_year) /* line 36 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->genre) /* line 37 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->total_copies) /* line 38 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText($b->available_copies) /* line 39 */;
			echo '</td>
                <td>';
			echo LR\Filters::escapeHtmlText(($this->filters->date)($b->added_at, 'd.m.Y')) /* line 40 */;
			echo '</td>
                <td>
                    <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('default', ['id' => $b->id])) /* line 42 */;
			echo '" class="btn edit">Upravit</a>
                    <a href="';
			echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('delete!', ['id' => $b->id])) /* line 43 */;
			echo '"
                       onclick="return confirm(\'Opravdu smazat tuto knihu?\')"
                       class="btn delete">Smazat</a>
                </td>
            </tr>
';

		}

		echo "\n";
		if (!count($books)) /* line 50 */ {
			echo '            <tr>
                <td colspan="10" style="text-align:center; color:#777;">
                    Žádné knihy zatím nejsou přidány.
                </td>
            </tr>
';
		}
		echo '    </table>
</div>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['b' => '30'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
